modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="meatmod"
version="1.01.19.2"
displayName="Meet The Meat!"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="sawilove"
description='''
Eat some delicious meat from exotic animals!
'''

[[dependencies.meatmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




